name: Automated tests
variables:
  python.version: '3.7.6'
  PUBLIC_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD2DdxPjYlEW96uIweui4EyRDLh6zP52Mu5eLAuWyQlxgzph2Zw9Im/TpVfemw1NZGLQYL5rd+kMALPM7DglLjW/XINJ/GG+XP778SgnDXBtm9FCQP/GIgRuMYTPSEvtHt16WwL1TWIHbcBO17frd5aZ300GUCSviLw4q7i6EhHMcuNlAMTuTfNrwxW48TuH2C+11qItDJZdzHyBhu9ncFweRa7af2NqFLTVNuIQtTRz/7hnuTGXf96o61TYDJY/YSqCWT7oEYCAkjvXfLgJ9Egdy19m3RBs0OGLYk3loRn7WBfUoyN/Uuq8NIwvg+cbouRrnWXBLf0DykfZqMs3IOAnd0NFyftbVxiQtO4lVXTYuIJtKpDL+mHVnPvIjKykXQxPGTYAbsKqU96aLW0AUTWvtfnwstKtOkmuw3QNK/i0HSuAoup/gEgFmxsm24BUcyYRPQxemNmxlQbm9iUQUIX8fLdaBI+AGTeBUyuRepyhOR/l8ssFU2rexFAfTvKXiFzbu/dZ0dBBLFKPSH7nsSgHQsovx/gWxqfzVllFyS945cWKNWa0wjmLFO0zQx5mOly82KXKJXIxo6VSbTsc7sKbSbYwApETCNT0edi8kgSVjj4p5H1uiUn6EcBBVMX6ELadIh4y3AgZ6bYm/jNtdnV4pJ00PrxGJ21x5uokziC7w== cjordan@cjordan-Aspire-VX5-591G'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    # Need for Terraform VM deployment
     - task: InstallSSHKey@0
       inputs:
        knownHostsEntry: "|1|ygTyu2u0HX8v129KIPlJo9AwenY=|haFgF662qkXP0kc4DQoPS3teU5Y= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
        sshPublicKey: $(PUBLIC_KEY)
        sshKeySecureFile: id_rsa.pub


       #login to azure account
     - script: 'az login --service-principal -u 26b6e71c-5dea-4977-969f-a9837ef76432 -p yg6Z1WGQ08Uqvk8-_Qa1gMXxWTlv-LxZKX --tenant 2cfcb216-ce47-4699-a281-2f1ee48e20f7'
       displayName: login to azure
       workingDirectory:  ./terraform
      
      #set resources on azure
     - script: 'terraform init'
       displayName: Initialise Azure Resources
       workingDirectory:  ./terraform
       #Clear resources on azure
     - script: 'terraform destroy -auto-approve -lock=false'
       displayName: Clear Azure Resources
       workingDirectory:  ./terraform
   


           

           